version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
    groups:
      android-build-tooling:
        patterns:
          - "com.android.tools.build:*"
          - "org.jetbrains.kotlin*"
      androidx:
        patterns:
          - "androidx.*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Kolkata"
    open-pull-requests-limit: 5
